FROM node:20-alpine

WORKDIR /app

# 빌드 결과물 복사
COPY build/dist ./dist
COPY build/package.json .
COPY build/package-lock.json .

# .env 파일도 사용하는 경우
# COPY build/.env .   # 필요 시 주석 해제

# 운영용 의존성 설치
RUN npm ci --omit=dev

EXPOSE 4000

CMD ["npm", "start"]
