# 1. Python 3.11 slim 이미지
FROM python:3.11-slim

# 2. 작업 디렉토리 지정
WORKDIR /app

# 3. build 폴더 내 모든 코드 복사
COPY build/ .

# 4. 의존성 설치
RUN pip install --no-cache-dir -r requirements.txt

# 5. 컨테이너 실행 시 run.py 실행해 플라스크 온
CMD ["python", "run.py"]


EXPOSE 5000